#+title: W4 Essay

** Introduction
The question of why some political regimes change into a new kind is a venerable
question in political science[fn:6]. In the last century, modernization
theory[fn:3] (in its economic, structural and cultural components) was the most
prominent attempt to tackle that. However, none of the contemporary descendants
of these views have been able to rigorously characterize why and how the current
wave of autocratization happens [[cite:&waldner2018unwelcome]] . The theoretical and
methodological developments of the last decades give us a rough indication that
an explanation requires a dual view: autocratization requires both supply and
demand. Understanding the causes and causal mechanisms of some elite actors not
wanting to play the democratic game anymore; gaining support from the
population; and other actors consistently failing to stop them, is an open
research agenda with the highest of societal stakes.

In this class paper, I'll define the classical perspective, conceptually clarify
what is meant by autocratization, and discuss how novel research is dealing with
this phenomenon.

** The classical views of democratization
Before dwelling on the traditional theories of democratization it is necessary
to have clarity on what is the underlying definition of democracy. According to
[[cite:&dahl1953]] (p.273), the First Problem of Politics is "how citizens can keep
their rulers from becoming tyrants"[fn:1]. This framing underlies most empirical
analysis of regimes and regime change ever since [[cite:&schumpeter2013capitalism]]
(p.269) defined democracy as

#+begin_quote
that institutional arrangement for arriving at political decisions in which
individuals acquire the power to decide by means of competitive struggle for the
people's vote.
#+end_quote

Most of the democratization literature assumes some variant of this definition
of democracy as competitive selection of rulers. An autocracy, then, is just a
political system in which rulers are not selected through a competitive struggle
for the people's vote.

Given this theoretical assumption, most works in the 60s sought to explain the
passage from autocracy to democracy in terms of broader social
"evolution"[[cite:&parsons1964evolutionary]]. That is, democracy is the
result of large-scale social modernization. What is meant by modernization
varies, though. Some explain it in terms of cultural change
[[cite:&eisenstadt1963political]], economic modernization [[cite:&lipset1959some]], or
class conflict dynamics [[cite:&moore1966]] .

As argued by [[cite:&geddes1999we,]] among those variants of modernization, the one
that garnered the most scrutiny, and that best withstood the test of time, is
the economic perspective of [[cite:&lipset1959some]]. He argues that economic
    development is highly correlated with democracy. Further refinement by the
    literature led to the general notion that democracy is more likely to happen the
    more developed is the country [[cite:&geddes1999we]].

The modern measurement of democracy tends to owe to the theoretical distinctions
laid out [[cite:&dahl2008polyarchy]]. Unlike most of his followers, Robert Dahl is
careful enough to understand democracy as an ideal, which has as key
characteristic being completely responsive to all its citizens. Polyarchy, what
is normally called "liberal democracy", is a regime inspired by this ideal, and
characterized by high levels of public contestation and inclusiveness. While
democracy would solve the problem of politics by collapsing the distinction of
rulers and citizens, polyarchy solves it by guaranteeing the inclusivity and
competitiveness of the process of selection of rulers. Thus, a country
with universal suffrage and competitive elections is a polyarchy[fn:8]. He
further derives 8 conditions that can be used to classify a country as
polyarchical, have served as guidelines in the operationalization of the concept
of "democracy" ever since
[[cite:&munck2002conceptualizing;&coppedge2002democracy;&schedler2001measuring]].:

1. Freedom to form and join organizations;
2. Freedom of expression;
3. Right to vote;
4. Right of political leaders to compete for support;
5. Alternative sources of information;
6. Eligibility for public office;
7. Free and fair elections;
8. Institutions for making government policies depend on votes and other
   expressions of preferences.

Another central contribution of this work is this simple proposition: the lower
the costs of toleration and the higher the costs of repression, the higher the
probability of a country transitioning to a competitive regime. Adam Przeworski
builds on that procedural perspective and in this notion of calculus of
oppression to understand the strategic incentives underlying the democratic game
and how they relate to economic development. He emphasizes the public
contestation aspect of the dahlsian polyarchical approach: parties lose
elections, and no single agent controls the outcomes of the electoral process
[[cite:&przeworski1991democracy]]. But why would agents comply to the rules of the
game? Precisely because no one controls the result of the process the
uncertainty of the result is an incentive for elites to try again and keep
playing the game. The dispersion of control of the outcome, the subjection of
interests to electoral competition, the decentralized self-interested punishment
of non-compliers and the institutionalization of the uncertainty inherent to the
electoral process, thus, is what he understands as democratization. For him a
democracy is consolidated when complying to it is the best an actor can do given
the decentralized best response of other actors [[cite:&przeworski2005democracy]].

But how is macro-context related to this micro-behavioral equilibrium? That is
where empirical research within the economic modernization theory appears in the
przeworskian research agenda: the more developed a place the higher the stakes
of deviating from the democratic equilibrium [[cite:&przeworski2005democracy]].
Thus, there is a positive association between economic development and
democracy, not because more developed countries are more likely to democratize,
but because authoritarian interventions are more unlikely in them
[[cite:&przeworski1997modernization]]. Note that a corollary of this is that lower
economic performance lowers the stake of deviating from democracy.

** On democratic demise

If taken as a system of concepts the classical perspectives are paramount to
understand the current autocratization wave [[cite:&luhrmann2019third]].
Nevertheless, the central stylized fact that came out of it, that economic
development and democracy are intimately related, is not enough to account for
this new phenomenon. Nor is the is the pre-dahlsian inclination to attempt to
correlate macro-variables without understanding their interactive
micro-foundations [[cite:&waldner2018unwelcome]].

Heretofore, autocratization means, as in [[cite:&luhrmann2019third]], the opposite
of democratization, where democratization will be understood as a movement
towards more inclusiveness and public contestation in the political system. Note
that in the literature different conceptualizations of states of affairs which
go against democratic values have been concocted, such as democratic backsliding
[[cite:&bermeo2016democratic]] , democratic rollback [[cite:&diamond2008democratic]],
authoritarian reversal [[cite:&svolik2008authoritarian]], democratic demise
[[cite:&schmitter1994dangers]], democratic breakdown [[cite:&svolik2015democracies]]. In
our conceptualization, autocratization is any movement towards autocracy,not
just the passage from democracy to autocracy. This inter-regime movement is a
special case of autocratization: whenever we stop calling a regime democratic
and start calling it an autocracy. The definition of a cut-off point is
obviously necessary lest one is led to a case of Sorites' paradox[fn:5].
Democratic breakdown, authoritarian reversal, democratic demise will be used
interchangeably when talking about this passage from democracy to autocracy,
while democratic backsliding/recession/roll will be any process of accumulation
of intra-regime "autocratization events", but which does not necessarily mean
the country has passed through the threshold of democracy to non-democracy.

Why focus on democratic backsliding rather than on democratic breakdown?
Precisely because of the specificities of the current wave of autocratization.
Rather than being characterized by a coup or overt autocratic maneuvers, as in
the last century, autocratization in countries such as Brazil, India, USA,
Türkiye, has happened as a cumulative process of "autocratization events", which
most of the time happen within the legal framework of the country
[[cite:&bermeo2016democratic]]. This requires an inferential/predictive stance
towards political events, but so does, say, talking about "consolidation"
[[cite:&schedler2001measuring]]. One has to project the downs-stream effects of
political maneuvers. Focusing on the cases of democratic breakdown reduces the
number of false positives and simplifies the large-N comparative analysis, at
the cost of not fully understanding of how it happens, or even characterizing
the process while it unfolds.

All in all, why is autocratization happening? And how does it happen? When does
it become a full-blown democratic breakdown?

** Causes

The case of full-blown breakdown, inter regime change, is better understood.
[[cite:&svolik2008authoritarian]] argues that a military past, low level of economic
development, and a presidential executive makes democracies less likely to
consolidate, where consolidation means "immunity" to reversals. However, among
those three factors only economic recessions matter for the timing of
authoritarian reversal. The notion of consolidation in this paper is problematic
for the analysis of democratic backsliding, or intraregime autocratization.
Consider the USA. It is typically deemed a consolidated democracy. Nevertheless,
the Trump administration is also considered a period of autocratization in the
country. The USA's democracy, however, did not breakdown, even after the
Capitol's invasion. Rather than immunity, or the equilibrium definition of
[[cite:&przeworski1991democracy]], consolidation can be defined as a higher
institutional resilience to autocratization events
[[cite:&page2012complexity;&schedler2001measuring]].

But why autocratization in general happens? There is, yet, no general
explanation [[cite:&waldner2018unwelcome]]. [[cite:&przeworski2020crises]] gives some
suggestions. We can split the question in 3.

- Why wannabe autocrats have such a large basis of support?
- Why part of the political class turn against the democratic status quo?
- Why aren't they stopped?

[[cite:&przeworski2019crises]] lists two possible macro causes for the election of
candidates who are not committed to the institutionalization of uncertainty:
first, and naturally, the economy is a cause; second, social and political
polarization. He argues that the economy might explain the ascension of those
candidates in two ways: one, globalization is leading to consistent losers, who
consistently vote for more extreme candidates; second, the share of the labor
factor of production in the social surplus has not risen as much as its
productivity. This "labor stagnation" or regress leads to a societal pessimism
that might explain why citizens subscribe to the discourse of magical solutions
as espoused by populists. This economic explanation naturally couples with the
rise of both political and social polarization. He argues that the level of
political polarization in the USA is an outlier, but there is a possible general
trend of strengthening of a second dimension of political conflict, beyond left
and right, related to values. He primarily talks about how immigration has
become such a focal point of conflict with the rise of a general conflict
between nationalist \(\times\) protectionists. Possible because it is still not clear
whether citizens vote for extremist candidates because they align ideologically
with them, or if they are just disillusioned with the political system.

Why would politicians turn against the status quo? Przeworki frames it as a
matter of (non)-punishment. Suppose you are a politician in power. You have an
incentive to try to bias the game in your favour if it enhances your chance of
staying in power and implementing its preferred policies in comparison to the
democratic status quo. What stops you is either the opposition or the citizens.
Thus, you make a calculus: every autocratic movement comes with a probability of
being punished. The size of the opposition it faces both from citizens and from
other actors will explain if the politician makes those moves
[[cite:&przeworski2019crises]].

That "calculus of opression", explains why they do not openly violate formal
rules of the game, until they either sway part of public opinion against those
rules or gain control of them. Moreover, this leads to a response to why they
are not stopped: first, they tend to have public support; second, they kidnap
the democratic discourse while using institutions' interpretive ambiguity to
bias the game in their favor. The opposition, then, has to argue that their
intentions are not democratic, which obviously is not objective. This democratic
response inertia gives leeway to the slow erosion of first the expectation
punishment and compliance, then to the slow subversion of formal rules and
finally to the control of key public contestation institutions, like the media,
the electoral system and the judicial system
[[cite:&waldner2018unwelcome;&przeworski2019crises;&bermeo2016democratic]].

Let me elaborate on the notion of "autocratization event". To prevent false
positives in the characterization of democratic backsliding
[[cite:&waldner2018unwelcome]] argues it must be an intended effort to impact at
least two of three dimensions of democratic governance: competition,
participation and accountability. So, what are such events? There is a clear
pattern. [[cite:&bermeo2016democratic]] lists some of them. Coups, either military
or self-coups are out of fashion. Promissory coups, however, are part of the
imaginary of many of those wannabe autocrats. In Brazil, Bolsonaro spent most of
his mandate talking about a necessity of a temporary coup to clean the political
system and then reinstate democracy. The 2009 coup and subsequent election in Honduras is
an example.

Executive aggrandizement is maybe the most general pattern. It happens when the
executive power weakens checks on it. This typically happens by
weakening/controlling the media and controlling/attacking the judiciary. If
politicians cannot directly control it, they seek to undermine its legitimacy,
like Bolsonaro and Trump. However, if they can control it, they don't need to
undermine it, like in Turkey and in India. Their behavior toward the judicial
system is similar. They generally attack it as undemocratic, while seeking to
change the number of Supreme/Constitutional court members so to appoint the new
members and gain a majority, as in Hungary or Turkey (and intended in Brazil).

Another well-known autocratization maneuver is election manipulation. A typical
strategy is to harass opposition voters to either abstain or to change their
vote. Harassment of opposition candidates is also normal. A more subtle example
happening in Brazil is timing social policies so that easier credit, debit
forgiveness, program expansion, all happen close to national elections.

** Limitations

The primary limitation of current attempts to explain autocratization is an
implicit focus on the USA/Europe, even among studies that do quantitative
large-N analysis
[[cite:&przeworski2019crises;&cassani2020reversing;&luhrmann2019third;&bermeo2016democratic;&waldner2018unwelco]].
Non-consolidated democracies undergoing autocratization are only used as
examples of where consolidated democracies might end up, without taking into
account that their autocratization may be deeper precisely because of their lack
of institutional resilience. Consider Latin America. First, the emergence of a
new axis of conflict in the region is not related to globalization or
immigration, but rather religious/conservative mores, since immigration is not a
social issue there. Second, in Latin America both the army and the police force
have been involved in autocratization movements, particularly in Brazil's
Bolsonaro government and in Bolivia's 2019 coup. This points out to the
importance of transition trajectories and how remnants of the old regime might
be used as an additional resource for wannabe autocrats, unlike in either
consolidated democracies or in transitional democracies which took a different
transitional justice path, like Chile [[cite:&nalepa2022after;&geddes1999we]].

Another problem in the literature is the assumption that macro economic and
cultural chances creates the demand for autocratization, without taking into
account how anti-democratic elites intentionally reinforce the radicalization
process. The current perspectives in political science don't seem to relate this
support base with a change in information technology and the emergence of a
parallel digital space, and whether those candidates' strategies within this
space have any impact on their continuous support [[cite:&waldner2018unwelcome]].
They also tend to have a high number of aggressive core supporters. In Brazil
they're circa 20% of the electorate. How do those politicians use the digital
social space to radicalize them?

We also don't understand enough the micro-foundations of autocratization. If
 formal democratic institutions are not enough to control autocratic candidates
 who were democratically elected, then it is necessary to have a theory of
 points of failure. The general contour is laid. The interpretative ambiguity of
 laws, their reliance of complementary informal institutions, the usage of
 seemly unrelated rules for electoral advantage or executive aggrandizement, are
  consistent points of failure exploited by wannabe autocrats
 [[cite:&przeworski2020crises;&bermeo2016democratic]]. We know they'll use those
 strategies to try to control the media, to gain power, control the judicial
 system, bias the electoral system, but what is the full course of strategies
 being used? What kind ambiguities are being exploited? Which kinds of seemly
 unrelated institutions are being combined with autocratic intentions? What
 kinds of complementary informal democratic institutions are being perverted?
 Again, this requires inferring downstream effects that might be impossible
 to predict ex-ante, but we can analyze ex-post what is already being done. This
 knowledge is not only scientifically necessary, but might have the practical
 implication of giving early warnings to oppositions in places in which
 autocratization has not yet taken place.


* Footnotes
[fn:8] Note, however, that in terms of propositions on why "democracy" develops
in some places and not in others [[cite:&dahl2008polyarchy]] does not fit the
characterization of a strict economic modernization theorist, since he considers
that culture, class conflict path and economic development all have some impact
on the odds of democratization.

[fn:6] It dates back to Aristotle.

[fn:5] Suppose you have a heap of sand. Now remove a grain of sand. Loop. When
does it stop being a heap ? A typical solution is establishing a boundary at
which a heap becomes a non-heap [[cite:&sep-sorites-paradox]].

[fn:3] Some of the literature reserves the term "modernization theory" to
Lipset's theory and the literature that ensues. I'm following
[[cite:&skocpol1973critical]] in using "modernization theory" in this broader
perspective.

[fn:1] If this is the first problem of politics one might wonder what to call
the problem: Why should we have rulers? [[cite:&graeber2004fragments]] Maybe the 0th
problem of politics. But again, why associate, after all?
[[cite:&buchanan1975limits]] Obviously, this is purely counterfactual, so maybe we
can call it the sqrt(-1)-th problem of politics.
