#+title: Emails
* First response email
Dear Marcelo,

Here is your paper with my specific comments. Next time, it would be better to use a Word version since the option of Track Changes is more flexible than Comments in pdf. A. If you make the corrections that I suggested, I can accept the paper as your first qualifier. After making all the corrections, you can look for the second reader. I suggest Bernie Grofman, Tony Smith, Carole Uhlaner, or Rein Taagepera. You may choose the same person with whom you took the class.

General comment about the style: you write well but you are mixing two different modes of analysis and the associated languages/concepts. Namely, social choice/voting theory uses standardized normatively neutral language that evaluates outcomes while “democratic backsliding,” “far right,” "extremist," etc. involve normative evaluations that, in my view, should be totally eliminated from our research. I use all such concepts with a lot of caution since I am painfully aware how ignorant and biased are those people who use such concepts with respect to Poland.

MAIN (AND BIG) PROBLEM: You have done a good job with the simulations and also with the application of the procedure of expanding the prefs with missing alternatives (but you need to explain this procedure in full detail). However, there is one big problem here that undermines the interpretation of your conclusions. Namely, the election data and the survey data are not compatible since in the survey, Bolsonaro gets substantially FEWER votes than in actual elections. The percentages obtained by different candidates are as follows:

    Bolsonaro:Haddad:Cirro:Alckmin
    Elections: 46.3:29.28:12.47:4.76
    Elections after removing blanks: 50.74:32.1:13.67:5:22
    Survey (first prefs total): 39.6:26.6:18.7:15.1


In order to equalize the first votes in the elections and the survey, one needs to re-weight the survey results. This would increase the frequency of prefs that start with Bolsonaro and Haddard, and decrease the others. The expected results (my guess):

Firstly, Bolsonaro would be a clear Condorcet winner and also Borda winner.

Secondly, Haddard would no longer be the Condorcet loser.

Thirdly, Alckmin would probably be Borda and will stay to be plurality loser

Finally, Haddad may become aniplurality loser but it may be a close race with Bolsonaro

You can do the following (it is not necessary for the acceptance as a qualifier but it is necessary if you want to have this piece published): You can re-do the simulations with weighted survey results. The incompatibility between the survey and the elections can be theorized to be caused by several factors, including problems with the survey itself, bias introduced by reconstructing full prefs, reluctance of voters to admit that they prefer Bolsonaro, a shift in voter prefs after the survey, or some joint impact of those factors. I cannot say in advance which ones of those hypotheses look more plausible. In Polish elections of 1991 (the first free after the fall of communism), there was a curious effect that might be also present in Brazil: in pre-election surveys, respondents substantially overweighted the centrist parties, and clearly underweighted the "extremes", i.e., the post-communist left and the anti-communist right.

MINOR ISSUES:

Note that Borda is VERY sensitive to including/removing candidates. Removing Ciro or Alckmin would likely make Bolsonaro the Borda winner even without re-weighting survey results.
Question: Where did you submit the paper?
If you would like to talk on Zoom, please let me know.

Cheers,
m
