#+title: General

* ps 2023 iteration
** Thomsen

- elections typo

- Introduction
  #+begin_quote
Great to state findings explicitly up front. That always bodes well for a paper. I do think you could build up the question a bit more though first and especially with respect to whatever the conventional wisdom is re: the 2018 Brazilian election.
  #+end_quote
- Develop better the social choice literature linking;
- She wonders how abstention would change my results
  - I 100% agree
- put percentage sign in stuff. keep at one decimal point.
- she was confused by the sentence saying that not everybody comparing all candidates. explain this better.
- end of section 3
  #+begin_quote
I'm not sure about this, but I wondered if some of the discussion of the case should go into the introduction and this section should give more attention to the survey, missing values, and possibly combined with the methods section.
  #+end_quote
- beginning of section 4: footnote should go after period
- she complained about the opened tetrahedron
  - maybe show it next to the other triangle
- on alckmin not ever beating bolsonaro as surprising: *explain it better*
  #+begin_quote
Can you elaborate on why this is surprising because Alckmin was in 4th in the vote so it doesn't seem that surprising (or is it the 0.0 value in particular that's surprising?).
  #+end_quote
- she argues that abstention could also be bolsonaro supporters. make sense. *must make this caveat*
- conclusion:
  #+begin_quote
discuss more the incomplete pairwise comparison thing. it was not clear for her.
  #+end_quote
- final comment
  #+begin_quote
Interesting paper and important topic. The counterfactual analysis was really terrific. My main suggestion is to build up the front end more -- what would be the conventional wisdom, how are the findings consistent with that or do they challenge that? Also hooking the paper a bit more to a specific literature in the first two pages might be helpful for narrowing the scope and setting clear parameters for which audience you're trying to engage with. I'd also appreciate more discussion of application to other contexts (either within Brazil or not) in the opening pages. Well written and compelling paper. Grade: A
  #+end_quote


** Udita


- conclusion
  #+begin_quote
In some other longer paper you might choose to demonstrate exactly how this is a critical juncture by situating the structural and contingent conditions that make it a critical juncture, and where the voting systems falls among those conditions
  #+end_quote
  - *makes sense*.I'm not satisfied with the critical juncture emphasis in the
    title and abstract. it doesn't appear much in my article.
  - the complained the "second, from a normative perspective". Maybe put a ":" after the perspective
** kaminski
Marcelo,

Your paper is much stronger than the first version that I recall. It is interesting and *quite* well-written (suggestions on what to do follow in the last comment). Certainly, it is fine as a qualifier. I think that if you take two actions: rewriting (necessary) and using an alternative method to correct for poll bias, the paper can be submitted to Public Choice or a similar journal. My comments follow below.

Page 7

The outcome simplex and the interpretation is correct but the triangle should have been more reminiscent of an equilateral triangle (two-dimensional simplex); for now, the base is too long.


Page 8



When you discuss the pairwise comparisons and the data from Table 3, be specific that you are talking about Round 1 (Blosonaro is a CW) versus R2 (unclear whether Ciro would have won against Bolsonaro). Otherwise, one gets the impression that you are making contradictory statements.


Page 9

When you refer to Figure 3 (the black upside triangle etc.), it is unclear what you mean since the black triangles, etc. in this figure are small. Enlarge them or explain them better.


Statement: Note, however, that Haddad only does well in a small region of the hull. Moreover, we

can see that there are decision procedures in which even Alckmin would have beaten both

Bolsonaro and Haddad.



This is imprecise at this point although this is clarified later. I marked in Figure 3 the regions where Haddad or Bolsonaro are winners (yellow vs yellow dots) (you can do that as well); the hulk has an empty intersection with the Haddad region as well as with the winning region for Alckmin. It seems that only Bolsonaro or Ciro could be winners under the scoring procedures in question. So, what does it mean that Haddad does well?

You should explain two things:

(1) What are the winning regions for all four candidates in a four-some contest?

(2) In a pairwise contest, what is the winning region for each candidate?

A mathematically sound reader can figure this out but others may be lost.


algebraic manipulation of the equations in Table 4 allows us to answer this question




